stages:
    - build
    - prepare
    - push
    - release

build:
    image: apertia/autocrm-dev
    stage: build
    only:
        - tags
    script:
        - npm config set -- //${CI_SERVER_HOST}/:_authToken=${PACKAGE_REGISTRY_TOKEN}
        - npm install
        - npm run build
    artifacts:
        paths:
            - node_modules/
            - dist/

prepare_push:
    stage: prepare
    only:
        - tags
    script:
        - export VERSION=$(cat package.json | jq -r '.version')
        - echo "VERSION=$VERSION" >> vars.env
        - echo "PACKAGE_NAME=$(ls -t dist/*.zip | head -1 | xargs -n 1 basename)" >> vars.env
        - echo "PACKAGE_REGISTRY_URL=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${VERSION}" >> vars.env
    artifacts:
        reports:
            dotenv: vars.env
        paths:
            - dist/

push:
    stage: push
    image: curlimages/curl:latest
    needs:
        -   job: prepare_push
            artifacts: true
    only:
        - tags
    script:
        - ls dist
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${PACKAGE_NAME} "${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}"
    artifacts:
        paths:
            - dist/


release:
    image: registry.gitlab.com/gitlab-org/release-cli
    stage: release
    only:
        - tags
    script:
        - >
            release-cli create --name "Release $CI_COMMIT_TAG"
            --description "Automated release $CI_COMMIT_TAG"
            --tag-name $CI_COMMIT_TAG --ref $CI_COMMIT_SHA
            --assets-link "{\"name\":\"${PACKAGE_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}\"}"
    artifacts:
        paths:
            - dist/

